### ISSUE TITLE
Multiple applications problem

### ISSUE THREAD

**Issue by sveins12** [faresamr/AspNetCore.Identity.Stores#12]
Hi this works great, but I have an issue. I have two applications, app-A and app-B using the same Cosmos database and same configurations. If I register a user with app-A, I can only sign in using the same app. Signing in with the other app gives an exception. The same the other way around, if I register with app-B I cannot sign in with app-A.

This is the exception I get:
System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning ....

Is there a secret key somewhere that is different for each application?

**Comment by sveins12** [comment]
Just found out. Have to set up application discrimination.

**Comment by silvacaio** [comment]
@sveins12 how you resolve that? I have the same problem, but the message is:
"The key {some-guid} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning"

**Comment by sveins12** [comment]
> @sveins12 how you resolve that? I have the same problem, but the message is: "The key {some-guid} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning"

@silvacaio, Yes, I configured data protection in the program startup. Like this:

```C#
builder.Services.AddDataProtection()
   .SetApplicationName("my-common-app-name")
```
The name should be the same for all applications using the same keys.

Additionaly, as I am running on IIS I also had to add the following, so that all the applications store the keys in the same folder.
```C#
 .PersistKeysToFileSystem("C:.....") 
```
I then copied the existing keys from registry into files in this folder, and then all applications could find them.
