### ISSUE TITLE
Multiple auth applications does not work 

### ISSUE THREAD

**Issue by silvacaio** [faresamr/AspNetCore.Identity.Stores#13]
Hi, I have the same problem that was reported on #12 

But with that message:
"The key {some-guid} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning"

The Identity uses some local key?

**Comment by faresamr** [comment]
As @sveins12 mentioned in his reply to your question in [#12](https://github.com/faresamr/AspNetCore.Identity.Stores/issues/12#issuecomment-1274974991)
Asp Identity uses [Data Protection system](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0) to encrypt protected data and to isolate applications, to prevents the apps from understanding each other's protected data.

If you want to share the data store between apps, you have to configure Asp Data Protection with the same key across all applications by using [SetApplicationName](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0#setapplicationname) as the application name is being used for encryption seeds.
```
builder.Services.AddDataProtection()
    .SetApplicationName("<sharedApplicationName>");
```

And for 
> "The key {some-guid} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning"

Please check [Key management in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-6.0) and the following thread from [stackoverflow](https://stackoverflow.com/questions/63316682/the-key-was-not-found-in-the-key-ring-unable-to-validate-token)

if you still have issues, please share more details about your setup.
