### ISSUE TITLE
Seeding for Roles, Admin user, and business related

### ISSUE THREAD

**Issue by chrisalexl2020** [faresamr/AspNetCore.Identity.Stores#5]
I have tried your NuGet package, which I assume this code for. I would like to verify is it a full implantation with Seeding for Roles, Admin User, and maybe the business side implementation (Catalog) on top of Identity? thanks.

**Comment by faresamr** [comment]
Hi Christopher,
Thank you for reaching out, a new version has been released and it will provide a way for [Seed Users and Roles Data](https://github.com/faresamr/AspNetCore.Identity.Stores/blob/main/docs/SeedUsersAndRolesData.md#seed-users-and-roles-data)

And for the business side unfortunately you need to implement your own admin portal, you can find here [IdentityManager](https://github.com/mguinness/IdentityManager) a simple implementation for controllers to manage roles and users

Also, I have created a new issue #7 Migrate to .Net 6 

Please feel free to reopen this issue or create a new one if you have any question.
